In [1]:
import pandas as pd

In [3]:
df= pd.read_csv('output_sas_comp.csv')

In [4]:
df.head()

,Country,CancerType,Incidence,Population,prevalence,Alive,Year,DeathCount,prevalence_1_year,diff
0,Alabama,Female Breast,18227.0,12434320,"0,15",1865148,2011-2015,3394,"0,150272954",0.0
1,Alaska,Female Breast,2100.0,1751388,"0,12","210166,56",2011-2015,310,"0,120177254",0.0
2,Arizona,Female Breast,22214.0,16686987,"0,13","2169308,31",2011-2015,3957,"0,130237112",0.0
3,Arkansas,Female Breast,10399.0,7527040,"0,14","1053785,6",2011-2015,2050,"0,140272405",0.0
4,California,Female Breast,128452.0,96473279,"0,13","12541526,27",2011-2015,22033,"0,130228382",0.0

In [5]:
df.tail()

,Country,CancerType,Incidence,Population,prevalence,Alive,Year,DeathCount,prevalence_1_year,diff
46,Washington,Female Breast,27427.0,20973326,"0,16","2798896,48",2011-2015,5427,"0,133709026",0.0
47,West Virginia,Female Breast,7252.0,17493103,"0,15","702372,6",2011-2015,4151,"0,040388718",0.0
48,Wisconsin,Female Breast,22561.0,4682484,"0,16","2311418,88",2011-2015,1453,"0,49394125",0.0
49,Wyoming,Female Breast,1830.0,14446368,"0,13","184415,27",2011-2015,3764,"0,013026042",0.0
50,NaN,Female Breast,NaN,1418579,NaN,NaN,2011-2015,316,NaN,NaN